### ISSUE TITLE
编得过，开不起

### ISSUE THREAD

**Issue by Niteip** [xuejianxin/testheart#1]
07-23 13:30:31.684 2373-2373/com.example.administrator.testheart E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.example.administrator.testheart, PID: 2373
                                                                                   java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.administrator.testheart/com.example.administrator.testheart.TypeTextViewActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.administrator.testheart.TypeTextViewActivity" on path: DexPathList[[zip file "/data/app/com.example.administrator.testheart-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.administrator.testheart-2/lib/x86, /vendor/lib, /system/lib]]
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.administrator.testheart.TypeTextViewActivity" on path: DexPathList[[zip file "/data/app/com.example.administrator.testheart-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.administrator.testheart-2/lib/x86, /vendor/lib, /system/lib]]
                                                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                       at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
                                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
                                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                                   	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.example.administrator.testheart.TypeTextViewActivity" on path: DexPathList[[dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-support-annotations-24.2.1_4824acc319c1f99634c95f48c6e2d6f915cd5905-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_a71c3c1dc47c3025cb11cb8c5c42c454d90501e6-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_894dcace0a8300b4c487b6ebce2cbc2965cfebaf-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_69afaab6a7cbaf08b1b1afb3a0fc712777cdf62a-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_61deafac68b54d1723da138c41279c1f65760a93-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_4cda033b88bda063be74248887baa30fdf181f7
07-23 13:30:39.167 2373-2373/com.example.administrator.testheart I/Process: Sending signal. PID: 2373 SIG: 9

**Comment by xuejianxin** [comment]
So you mean the project can be run properly, but it doesn't work properly?

At 2017-07-23 21:31:44, "Niteip" <notifications@github.com> wrote:


07-23 13:30:31.684 2373-2373/com.example.administrator.testheart E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.administrator.testheart, PID: 2373
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.administrator.testheart/com.example.administrator.testheart.TypeTextViewActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.administrator.testheart.TypeTextViewActivity" on path: DexPathList[[zip file "/data/app/com.example.administrator.testheart-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.administrator.testheart-2/lib/x86, /vendor/lib, /system/lib]]
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2327)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.administrator.testheart.TypeTextViewActivity" on path: DexPathList[[zip file "/data/app/com.example.administrator.testheart-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.administrator.testheart-2/lib/x86, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
at android.app.Instrumentation.newActivity(Instrumentation.java:1067)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
at android.app.ActivityThread.-wrap11(ActivityThread.java) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:148) 
at android.app.ActivityThread.main(ActivityThread.java:5417) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.example.administrator.testheart.TypeTextViewActivity" on path: DexPathList[[dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-support-annotations-24.2.1_4824acc319c1f99634c95f48c6e2d6f915cd5905-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_a71c3c1dc47c3025cb11cb8c5c42c454d90501e6-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_894dcace0a8300b4c487b6ebce2cbc2965cfebaf-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_69afaab6a7cbaf08b1b1afb3a0fc712777cdf62a-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_61deafac68b54d1723da138c41279c1f65760a93-classes.dex", dex file "/data/data/com.example.administrator.testheart/files/instant-run/dex/slice-internal_impl-24.2.1_4cda033b88bda063be74248887baa30fdf181f7
07-23 13:30:39.167 2373-2373/com.example.administrator.testheart I/Process: Sending signal. PID: 2373 SIG: 9
